### ISSUE TITLE
Now this is support AWS S3?

### ISSUE THREAD

**Issue by TopGun008** [TileDB-Inc/TileDB-Spark#75]
here is my code.
`val simpleDF = spark.read.format("io.tiledb.spark").option("vfs.s3.scheme","http").option("vfs.s3.endpoint_override","http://127.0.0.1:9000").option("vfs.s3.connect_timeout_ms","60000").option("vfs.s3.aws_access_key_id","minioadmin").option("vfs.s3.aws_secret_access_key","minioadmin").option("uri","s3://testtiledb/quickstart_dense_array").option("read_buffer_size", 250*1024*1024).load()`

**Comment by Shelnutt2** [comment]
@TopGun008 S3 is full support by TileDB and TileDB-Spark. I believe what your problem is that TileDB config options need to be prefixed with `tiledb.` Please try the following:

```
val simpleDF = spark.read.format("io.tiledb.spark")
.option("tiledb.vfs.s3.scheme","http")
.option("tiledb.vfs.s3.endpoint_override","http://127.0.0.1:9000")
.option("tiledb.vfs.s3.connect_timeout_ms","60000")
.option("tiledb.vfs.s3.aws_access_key_id","minioadmin")
.option("tiledb.vfs.s3.aws_secret_access_key","minioadmin")
.option("uri","s3://testtiledb/quickstart_dense_array")
.option("read_buffer_size", 250*1024*1024).load()
```

**Comment by TopGun008** [comment]
I am very happy to solve my problem, Thank you for your help.

**Comment by TopGun008** [comment]
When i try this,it always get "Internal TileDB uncaught exception; std::bad_alloc" error,which when use C++ code to read without any error.
`val sampleDF = spark.read.format("io.tiledb.spark")
    .option("uri", "file:///mypath/quickstart_dense_array")
    .option("read_buffer_size", 64).load()`

**Comment by Shelnutt2** [comment]
If you are having `bad_alloc` then it is likely you are running out of memory. How many fields are you selecting? The `read_buffer_size` is per field you the total TileDB memory is `field_count * read_buffer_size`.  Another factor you need to consider is if you are running multiple tasks per executor this can also increase the memory requirements. See the [performance tips](https://docs.tiledb.com/spark/performance-tips) section of the docs for some details and breakdown about running multiple tasks vs one task per executor.

Another thing to consider is how much off heap memory (`spark.yarn.executor.memoryOverhead`) did you allow? If you left this at the default of 10% this could be why you are running into problems also.

Lastly just a note, the 64 byte buffers `.option("read_buffer_size", 64)`, are incredible small and not likely to perform well. I image you were just trying very small buffers to avoid the bad_alloc but I wanted to point it out.

**Comment by TopGun008** [comment]
Thank you for you help, I found that TileDB-Java(0.3.6) causes`Internal TileDB uncaught exception; std::bad_alloc` when I run TileDB-Java Single.

**Comment by gsvic** [comment]
Hi @TopGun008. Could you share us you TileDB-Java code, so we can test if there is some specific issue related to the `0.3.6` version?

**Comment by TopGun008** [comment]
When create ArraySchema, “ArraySchema arraySchema = new ArraySchema(ctx,
                    "/home/quickstart_dense_array")” show ` Internal TileDB uncaught exception; std::bad_alloc` error, what is wrong with my code? Thank you for your help.
`public static void main(String []args) {
        System.out.println("hello world!");
        try (Context ctx = new Context()) {
            // Create array schema
            ArraySchema arraySchema = new ArraySchema(ctx,
                    "/home/quickstart_dense_array");
            arraySchema.dump("/home/arrayScheme.txt");
      
        } catch (TileDBError e) {
           System.out.println(e.getMessage());
        }
    }`

**Comment by gsvic** [comment]
@TopGun008 Could you share the code you use in order to create the array  `/home/quickstart_dense_array`?

**Comment by TopGun008** [comment]
@gsvic here is that code create array. It is C++ code.
`void create_array() {
    // Create a TileDB context.
    Context ctx;

    // The array will be 4x4 with dimensions "rows" and "cols", with domain [1,4].
    Domain domain(ctx);
    domain.add_dimension(Dimension::create<int>(ctx, "rows", {{1, 4}}, 4))
            .add_dimension(Dimension::create<int>(ctx, "cols", {{1, 4}}, 4));

    // The array will be dense.
    ArraySchema schema(ctx, TILEDB_DENSE);
    schema.set_domain(domain).set_order({{TILEDB_ROW_MAJOR, TILEDB_ROW_MAJOR}});

    // Add a single attribute "a" so each (i,j) cell can store an integer.
    schema.add_attribute(Attribute::create<int>(ctx, "a"));

    // Create the (empty) array on disk.
    Array::create(array_name, schema);
}`
`void write_array() {
    Context ctx;

    // Prepare some data for the array
    std::vector<int> data = {
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

    // Open the array for writing and create the query.
    Array array(ctx, array_name, TILEDB_WRITE);
    Query query(ctx, array, TILEDB_WRITE);
    query.set_layout(TILEDB_ROW_MAJOR).set_buffer("a", data);

    // Perform the write and close the array.
    query.submit();
    array.close();
}`
Thanks!

**Comment by gsvic** [comment]
@TopGun008 I tested the code you've sent me, I created the array with the C++ code and then dumped the schema with the TileDB-Java 0.3.6 version but I was not able to reproduce the error on a OS Catalina 10.15.7. What OS do you run?

I am wondering if something went wrong during array creation. Could you please try to completely delete the array and re-create it? Then try to dump the schema with the Java code again.

Here is the code that I used in my test:

```
#include <tiledb/tiledb>

using namespace tiledb;

void create_array() {

 std::string array_name = "sample_array";

 // Create a TileDB context.
 Context ctx;

 // The array will be 4x4 with dimensions "rows" and "cols", with domain [1,4].
 Domain domain(ctx);
 domain.add_dimension(Dimension::create<int>(ctx, "rows", {{1, 4}}, 4))
        .add_dimension(Dimension::create<int>(ctx, "cols", {{1, 4}}, 4));

 // The array will be dense.
 ArraySchema schema(ctx, TILEDB_DENSE);
 schema.set_domain(domain).set_order({{TILEDB_ROW_MAJOR, TILEDB_ROW_MAJOR}});

 // Add a single attribute "a" so each (i,j) cell can store an integer.
 schema.add_attribute(Attribute::create<int>(ctx, "a"));

 // Create the (empty) array on disk.
 Array::create(array_name, schema);
}

void write_array() {
  Context ctx;

  std::string array_name = "sample_array";

  // Prepare some data for the array
  std::vector<int> data = {
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

  // Open the array for writing and create the query.
  Array array(ctx, array_name, TILEDB_WRITE);
  Query query(ctx, array, TILEDB_WRITE);
  query.set_layout(TILEDB_ROW_MAJOR).set_buffer("a", data);

  // Perform the write and close the array.
  query.submit();
  array.close();
}

int main(){
  create_array();
  write_array();
}
```

**Comment by TopGun008** [comment]
OK, Thank you.My Testing OS is Ubuntu 18.04.5 LTS, 5.4.0-65-generic.
