### ISSUE TITLE
Publish on maven?

### ISSUE THREAD

**Issue by Hoeze** [TileDB-Inc/TileDB-Spark#78]
TileDB-java is on maven, but TileDB-spark is not.
Would it be possible to release maven artifacts as well?
This way, it would not be necessary to download the jars manually.

**Comment by Shelnutt2** [comment]
@Hoeze yes we can do this, we'll look to add it within the next week or two.

**Comment by Shelnutt2** [comment]
@Hoeze It took a bit longer than anticipated but @ihnorton just merged the publishing to maven central in #81 . We should be on maven central with the next release. Within the next few days we should have a snapshot version up in the maven central snapshot repo.

**Comment by Hoeze** [comment]
Cool, thanks a lot @ihnorton :+1:

**Comment by Hoeze** [comment]
@ihnorton I just tried the TileDB jar from maven:
```python
spark = (
    SparkSession.builder
    .appName('tiledb_spark')
    .config("spark.jars.packages", ",".join([
        "io.tiledb:tiledb-java:0.5.1",
        "io.tiledb:tiledb-spark:0.3.0",
    ]))
    .config("spark.local.dir", os.environ.get("TMP"))
    .config("spark.sql.arrow.enabled", "true")
    .getOrCreate()
)
```
Unfortunately, I got a `ClassNotFound` error when saving / loading TileDB.

Is this library compatible with the latest PySpark version v3.1.2?
