### ISSUE TITLE
Why does it take so much memory to convert to tiledb format in spark

### ISSUE THREAD

**Issue by LvLiangLiang-dev** [TileDB-Inc/TileDB-Spark#87]
![image](https://user-images.githubusercontent.com/19455764/128835081-a69a38b5-7968-4b6d-b69d-91520532a514.png)

pdf just is a 600MB file, Why does it take so much memory to convert to tiledb format in spark

**Comment by ihnorton** [comment]
Hi @Faynebupt,
Thanks for opening the issue. Could you please give some more information about the data/schema you are writing (eg number of columns, size on disk, etc.)
