### ISSUE TITLE
Does tiledb have a plan to connect to Clickhouse? 

### ISSUE THREAD

**Issue by 2021blackhole** [TileDB-Inc/TileDB-Spark#90]
Does tiledb have a plan to connect to Clickhouse? 
We use Clickhouse very much. 
I'd like to ask you about roadmaps of connecting to more computing engines.
tks

**Comment by 2021blackhole** [comment]
We especially like the features and capabilities of tiledb and hope to connect with more computing engines。

**Comment by Shelnutt2** [comment]
@2021blackhole we are always open to integrating TileDB with more compute engines or library such as clickhouse. We'd love to talk more about your use case and the computation engines you are looking for integrations with. If you'd like we can move the discussion from the issues to email. Feel free to reach out to me directly at `seth` @ `tiledb.com` or our general inbox of `hello@tiledb.com` and I'd love to setup a short call for us to discuss more.

Please also feel free to make suggestions or vote on roadmap features at our [canny roadmap and feedback site](https://feedback.tiledb.com). This helps us to see what the community is looking for us to prioritize.
