### ISSUE TITLE
speed about

### ISSUE THREAD

**Issue by 2021blackhole** [TileDB-Inc/TileDB-Spark#92]
We tested the speed of spark 2.4 native and spark 2.4 with tiledb as the storage engine to operate about 10g data for sum. Sadly, the time is almost the same, slower than spark 3.0 and more slower than Clickhouse;

Do you have similar improvement plans, 
1: improve the speed of spark with tiledb as the storage engine,
2: improve the ability to handle large single tables compared with Clickhouse

**Comment by ihnorton** [comment]
Hi @2021blackhole, thanks for opening the issue. I believe my colleague sent some responses to you directly by email as well -- but to respond to this question: yes, we are working on several performance improvements in the Java and Spark APIs; in particular, we will soon add support for Arrow buffers into TileDB-Spark. We are also continuously improving performance of the core library. There are several parameters which have a substantial performance impact, and would be happy to work with you to optimize your use-case if you are able to provide more details here or directly by email.
